services:
  store:
    image: antonsleptsov/store
    environment:
      - DB_HOST=storedb:5432
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_DBNAME=storedb
    ports:
      - 8080:8080
    networks:
      - store-network
    depends_on:
      - storedb
    restart: unless-stopped

  storedb:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=storedb
    networks:
      - store-network
    restart: unless-stopped
    volumes:
      - "/home/anton/home/volumes/boardGamesVolume/storeDbVolume:/var/lib/postgresql/data"

  reviews:
    image: antonsleptsov/reviews
    environment:
      - DB_HOST=reviewsdb:5432
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_DBNAME=reviewsdb
    ports:
      - 8081:8080
    networks:
      - store-network
    depends_on:
      - reviewsdb
    restart: unless-stopped

  reviewsdb:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=reviewsdb
    networks:
      - store-network
    restart: unless-stopped
    volumes:
      - "/home/anton/home/volumes/boardGamesVolume/reviewsDbVolume:/var/lib/postgresql/data"

networks:
  store-network:
