name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            antonsleptsov/bestboardgame
            antonsleptsov/boardgameofday
            antonsleptsov/reviews
            antonsleptsov/store
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push image for best board game
      - name: Build and push Docker image (bestBoardGame)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bestBoardGame  # путь к Dockerfile.bestBoardGame
          push: true
          tags: antonsleptsov/bestboardgame:${{ steps.meta.outputs.sha }}  # исправленный тег

      # Build and push image for board game of the day
      - name: Build and push Docker image (boardGameOfDay)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.boardGameOfDay  # путь к Dockerfile.boardGameOfDay
          push: true
          tags: antonsleptsov/boardgameofday:${{ steps.meta.outputs.sha }}  # исправленный тег

      # Build and push image for reviews
      - name: Build and push Docker image (reviews)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.reviews  # путь к Dockerfile.reviews
          push: true
          tags: antonsleptsov/reviews:${{ steps.meta.outputs.sha }}  # исправленный тег

      # Build and push image for store
      - name: Build and push Docker image (store)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.store  # путь к Dockerfile.store
          push: true
          tags: antonsleptsov/store:${{ steps.meta.outputs.sha }}  # исправленный тег

