name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push image for best board game
      - name: Build and push Docker image (bestBoardGame)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bestBoardGame  # путь к Dockerfile.bestBoardGame
          push: true
          tags: antonsleptsov/bestboardgame:latest  # явный тег

      # Build and push image for board game of the day
      - name: Build and push Docker image (boardGameOfDay)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.boardGameOfDay  # путь к Dockerfile.boardGameOfDay
          push: true
          tags: antonsleptsov/boardgameofday:latest  # явный тег

      # Build and push image for reviews
      - name: Build and push Docker image (reviews)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.reviews  # путь к Dockerfile.reviews
          push: true
          tags: antonsleptsov/reviews:latest  # явный тег

      # Build and push image for store
      - name: Build and push Docker image (store)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.store  # путь к Dockerfile.store
          push: true
          tags: antonsleptsov/store:latest  # явный тег
