name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Get commit hash and branch name
        id: vars
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub 
        uses: docker/login-action@v2 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push image for best board game
      - name: Build and push Docker image (bestBoardGame)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bestBoardGame
          push: true
          tags: |
            antonsleptsov/bestboardgame:${{ env.COMMIT_HASH }}
            antonsleptsov/bestboardgame:${{ env.BRANCH_NAME }}

      # Build and push image for board game of the day
      - name: Build and push Docker image (boardGameOfDay)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.boardGameOfDay
          push: true
          tags: |
            antonsleptsov/boardgameofday:${{ env.COMMIT_HASH }}
            antonsleptsov/boardgameofday:${{ env.BRANCH_NAME }}

      # Build and push image for reviews
      - name: Build and push Docker image (reviews)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.reviews
          push: true
          tags: |
            antonsleptsov/reviews:${{ env.COMMIT_HASH }}
            antonsleptsov/reviews:${{ env.BRANCH_NAME }}

      # Build and push image for store
      - name: Build and push Docker image (store)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.store
          push: true
          tags: |
            antonsleptsov/store:${{ env.COMMIT_HASH }}
            antonsleptsov/store:${{ env.BRANCH_NAME }}
